export const DOCS = [
  {
    id: "prd",
    n: "01",
    short: "PRD",
    title: "Product Requirement Document",
    purpose: "Tells the AI what to build",
    icon: "📋",
    goldenRule: "Clear PRD = 70% work already done",
    sections: [
      { id: "problem",       title: "Problem Statement",              hint: "What problem does this product solve?",                    kind: "block", rows: 4 },
      { id: "targetUsers",   title: "Target Users",                   hint: "Who is this for? Describe your primary user persona.",      kind: "block", rows: 3 },
      { id: "featuresBasic", title: "Feature List — Basic (MVP)",     hint: "List core features needed at launch, one per line.",       kind: "list" },
      { id: "featuresAdv",   title: "Feature List — Advanced",        hint: "Nice-to-have features for later versions, one per line.",  kind: "list" },
      { id: "userFlow",      title: "User Flow",                      hint: "Step-by-step journey from landing to goal.",               kind: "block", rows: 4 },
      { id: "techPrefs",     title: "Tech Preferences (Optional)",    hint: "Preferred languages, frameworks, platforms, hosting…",     kind: "line"  },
    ],
  },
  {
    id: "system",
    n: "02",
    short: "System Design",
    title: "System Design Document",
    purpose: "Tells the AI how to build it",
    icon: "🧠",
    goldenRule: "Clean, structured & scalable code",
    sections: [
      { id: "frontendArch",  title: "Frontend Architecture",          hint: "Framework, folder structure, state management, routing.",  kind: "block", rows: 4 },
      { id: "backendArch",   title: "Backend Architecture",           hint: "Language, framework, server structure, deployment.",       kind: "block", rows: 4 },
      { id: "apiStructure",  title: "API Structure & Flow",           hint: "List key endpoints. Format: METHOD /path — description",  kind: "list"  },
      { id: "dbSchema",      title: "Database Schema",                hint: "Tables/collections and fields. e.g. Users: id, name…",    kind: "block", rows: 5 },
      { id: "authSecurity",  title: "Authentication & Security Flow", hint: "Auth method, password hashing, role-based access…",       kind: "block", rows: 3 },
    ],
  },
  {
    id: "uiux",
    n: "03",
    short: "Wireframes",
    title: "UI/UX Wireframes",
    purpose: "Gives the AI visual and design clarity",
    icon: "🎨",
    goldenRule: "Better UI clarity = Less rework later",
    sections: [
      { id: "keyScreens",    title: "Key Screens",                    hint: "List screens: Home, Login, Dashboard, Profile, etc.",     kind: "list"  },
      { id: "layoutIdeas",   title: "Layout Ideas",                   hint: "Describe layout per screen or paste Figma links.",        kind: "block", rows: 4 },
      { id: "colors",        title: "Color Palette",                  hint: "Primary, secondary, accent, background colors (hex).",    kind: "block", rows: 2 },
      { id: "fonts",         title: "Fonts & Typography",             hint: "Heading font, body font, sizes, weights.",                kind: "block", rows: 2 },
      { id: "designStyle",   title: "Design Style",                   hint: "Minimal, glassmorphism, brutalist, dark-mode-first…",     kind: "line"  },
    ],
  },
  {
    id: "features",
    n: "04",
    short: "Features",
    title: "Feature Breakdown Document",
    purpose: "Breaks big features into step-by-step tasks",
    icon: "✅",
    goldenRule: "Helps AI build step-by-step, like a developer",
    sections: [
      { id: "featureList",   title: "Feature List",                   hint: "List all major features, one per line.",                  kind: "list"  },
      { id: "breakdowns",    title: "Feature Breakdowns",             hint: "Break each into sub-tasks:\nLogin:\n- Email validation\n- Auth flow", kind: "block", rows: 8 },
      { id: "priority",      title: "Priority Order",                 hint: "Rank features: P1 (critical), P2 (important), P3 (nice-to-have).", kind: "block", rows: 3 },
      { id: "dependencies",  title: "Dependencies",                   hint: "Which features depend on others? e.g. Dashboard requires Auth first.", kind: "block", rows: 3 },
    ],
  },
  {
    id: "master",
    n: "05",
    short: "Master Prompt",
    title: "Master Prompt Document",
    purpose: "Combines everything into one authoritative prompt",
    icon: "⚡",
    goldenRule: "This decides: Random code ❌ OR Production-ready output ✅",
    sections: [
      { id: "projectOverview",    title: "Project Overview",         hint: "One paragraph summary of the entire project for the AI.",  kind: "block", rows: 4 },
      { id: "strictInstructions", title: "Strict Instructions",      hint: "Rules AI must follow. e.g. Never use inline styles.",      kind: "list"  },
      { id: "techStack",          title: "Tech Stack",               hint: "Full stack: Frontend, Backend, Database, Auth, Hosting…",  kind: "list"  },
      { id: "codeStyle",          title: "Code Style Guidelines",    hint: "Naming conventions, file structure, commenting style.",    kind: "block", rows: 3 },
      { id: "outputFormat",       title: "Output Format",            hint: "How should AI output code? File names, folder structure.", kind: "block", rows: 3 },
    ],
  },
];
