export const DOCS = [
  {
    id: "prd",
    n: "01",
    short: "PRD",
    title: "Product Requirement Document",
    purpose: "Tells the AI what to build",
    icon: "📋",
    goldenRule: "Clear PRD = 70% work already done",
    sections: [
      { id: "problem",       title: "Problem Statement",              hint: "What problem does this product solve?",                    kind: "block", rows: 4 },
      { id: "targetUsers",   title: "Target Users",                   hint: "Who is this for? Describe your primary user persona.",      kind: "block", rows: 3 },
      { id: "featuresBasic", title: "Feature List — Basic (MVP)",     hint: "List core features needed at launch, one per line.",       kind: "list" },
      { id: "featuresAdv",   title: "Feature List — Advanced",        hint: "Nice-to-have features for later versions, one per line.",  kind: "list" },
      { id: "userFlow",      title: "User Flow",                      hint: "Step-by-step journey from landing to goal.",               kind: "block", rows: 4 },
      { id: "techPrefs",     title: "Tech Preferences (Optional)",    hint: "Preferred languages, frameworks, platforms, hosting…",     kind: "line"  },
    ],
  },
  {
    id: "system",
    n: "02",
    short: "System Design",
    title: "System Design Document",
    purpose: "Tells the AI how to build it",
    icon: "🧠",
    goldenRule: "Clean, structured & scalable code",
    sections: [
      { id: "frontendArch",  title: "Frontend Architecture",          hint: "Framework, folder structure, state management, routing.",  kind: "block", rows: 4 },
      { id: "backendArch",   title: "Backend Architecture",           hint: "Language, framework, server structure, deployment.",       kind: "block", rows: 4 },
      { id: "apiStructure",  title: "API Structure & Flow",           hint: "List key endpoints. Format: METHOD /path — description",  kind: "list"  },
      { id: "dbSchema",      title: "Database Schema",                hint: "Tables/collections and fields. e.g. Users: id, name…",    kind: "block", rows: 5 },
      { id: "authSecurity",  title: "Authentication & Security Flow", hint: "Auth method, password hashing, role-based access…",       kind: "block", rows: 3 },
    ],
  },
  {
    id: "uiux",
    n: "03",
    short: "Wireframes",
    title: "UI/UX Wireframes",
    purpose: "Gives the AI visual and design clarity",
    icon: "🎨",
    goldenRule: "Better UI clarity = Less rework later",
    sections: [
      { id: "keyScreens",    title: "Key Screens",                    hint: "List screens: Home, Login, Dashboard, Profile, etc.",     kind: "list"  },
      { id: "layoutIdeas",   title: "Layout Ideas",                   hint: "Describe layout per screen or paste Figma links.",        kind: "block", rows: 4 },
      { id: "colors",        title: "Color Palette",                  hint: "Primary, secondary, accent, background colors (hex).",    kind: "block", rows: 2 },
      { id: "fonts",         title: "Fonts & Typography",             hint: "Heading font, body font, sizes, weights.",                kind: "block", rows: 2 },
      { id: "designStyle",   title: "Design Style",                   hint: "Minimal, glassmorphism, brutalist, dark-mode-first…",     kind: "line"  },
    ],
  },
  {
    id: "features",
    n: "04",
    short: "Features",
    title: "Feature Breakdown Document",
    purpose: "Breaks big features into step-by-step tasks",
    icon: "✅",
    goldenRule: "Helps AI build step-by-step, like a developer",
    sections: [
      { id: "featureList",   title: "Feature List",                   hint: "List all major features, one per line.",                  kind: "list"  },
      { id: "breakdowns",    title: "Feature Breakdowns",             hint: "Break each into sub-tasks:\nLogin:\n- Email validation\n- Auth flow", kind: "block", rows: 8 },
      { id: "priority",      title: "Priority Order",                 hint: "Rank features: P1 (critical), P2 (important), P3 (nice-to-have).", kind: "block", rows: 3 },
      { id: "dependencies",  title: "Dependencies",                   hint: "Which features depend on others? e.g. Dashboard requires Auth first.", kind: "block", rows: 3 },
    ],
  },
  {
    id: "master",
    n: "05",
    short: "Master Prompt",
    title: "Master Prompt Document",
    purpose: "Combines everything into one authoritative prompt",
    icon: "⚡",
    goldenRule: "This decides: Random code ❌ OR Production-ready output ✅",
    sections: [
      { id: "projectOverview",    title: "Project Overview",         hint: "One paragraph summary of the entire project for the AI.",  kind: "block", rows: 4 },
      { id: "strictInstructions", title: "Strict Instructions",      hint: "Rules AI must follow. e.g. Never use inline styles.",      kind: "list"  },
      { id: "techStack",          title: "Tech Stack",               hint: "Full stack: Frontend, Backend, Database, Auth, Hosting…",  kind: "list"  },
      { id: "codeStyle",          title: "Code Style Guidelines",    hint: "Naming conventions, file structure, commenting style.",    kind: "block", rows: 3 },
      { id: "outputFormat",       title: "Output Format",            hint: "How should AI output code? File names, folder structure.", kind: "block", rows: 3 },
    ],
  },
  {
    id: "datamodel",
    n: "06",
    short: "Data Model",
    title: "Data Model Document",
    purpose: "Tells the AI how data is structured and related",
    icon: "🗄️",
    goldenRule: "No data model = inconsistent schemas and broken relations",
    sections: [
      { id: "entities",     title: "Core Entities",          hint: "List the main data entities, one per line. e.g. User, Post, Order, Product", kind: "list" },
      { id: "relationships",title: "Relationships",          hint: "Describe how entities relate. e.g. User has many Posts (one-to-many). Order belongs to one User.", kind: "block", rows: 4 },
      { id: "schema",       title: "Schema / Field Definitions", hint: "List fields per entity.\ne.g.\nUsers: id (UUID), email (string, unique), created_at (timestamp)\nPosts: id, title, body, user_id (FK)", kind: "block", rows: 8 },
      { id: "indexes",      title: "Indexes & Constraints",  hint: "Any fields that need indexes, unique constraints, or NOT NULL rules.", kind: "block", rows: 3 },
      { id: "storage",      title: "Storage Engine",         hint: "Where is the data stored? e.g. PostgreSQL, Supabase, Firebase, SQLite, localStorage, Redis…", kind: "line" },
    ],
  },
  {
    id: "security",
    n: "07",
    short: "Security",
    title: "Security & Compliance Checklist",
    purpose: "Ensures the AI builds safe, secure code by design",
    icon: "🔒",
    goldenRule: "Vibecoded code is NOT secure by default — make it explicit",
    sections: [
      { id: "threats",      title: "Top Threat Risks",       hint: "List the key threats for your app. e.g.\n- SQL injection via search input\n- Unauthorised access to other users' data\n- API key leakage in client-side code", kind: "list" },
      { id: "auth",         title: "Authentication & Authorisation", hint: "How are users authenticated? What can each role access? e.g. JWT, OAuth, Supabase Auth, RBAC, row-level security.", kind: "block", rows: 3 },
      { id: "dataPrivacy",  title: "Data Privacy Rules",     hint: "What sensitive data exists? How is it encrypted, masked, or excluded from logs? Any GDPR/HIPAA/CCPA requirements?", kind: "block", rows: 3 },
      { id: "inputRules",   title: "Input Validation Rules", hint: "List validation and sanitisation rules. e.g. Sanitise all HTML inputs, validate email format, max file size 5MB.", kind: "list" },
      { id: "secrets",      title: "Secrets Management",     hint: "Where do API keys and secrets live? e.g. Environment variables only, never in source code, use .env.example as template.", kind: "line" },
      { id: "compliance",   title: "Compliance Requirements", hint: "Any standards to follow? e.g. OWASP Top 10, GDPR, SOC 2, HIPAA, PCI-DSS, App Store privacy manifest.", kind: "list" },
    ],
  },
  {
    id: "testing",
    n: "08",
    short: "Testing",
    title: "Testing Strategy",
    purpose: "Tells the AI what tests to write and how to structure them",
    icon: "🧪",
    goldenRule: "AI skips tests unless you make them part of the brief",
    sections: [
      { id: "approach",     title: "Testing Approach",       hint: "Which levels of testing? e.g. Unit tests for utilities, Integration tests for API routes, E2E for critical user flows.", kind: "block", rows: 3 },
      { id: "happyPaths",   title: "Critical Happy Paths",   hint: "List the flows that must always work. e.g.\n- User signs up and receives confirmation email\n- User completes checkout\n- Admin can view all orders", kind: "list" },
      { id: "edgeCases",    title: "Edge Cases & Negatives", hint: "What should fail gracefully? e.g.\n- Invalid email format shows error\n- Payment failure shows retry screen\n- Empty search returns empty state", kind: "list" },
      { id: "tools",        title: "Testing Tools",          hint: "Which testing frameworks to use? e.g. Vitest + React Testing Library for unit/component, Playwright for E2E.", kind: "line" },
      { id: "coverage",     title: "Coverage Targets",       hint: "What % coverage is acceptable? e.g. 80% unit coverage, 100% on auth and payment flows. E2E: all critical paths.", kind: "line" },
    ],
  },
  {
    id: "deployment",
    n: "09",
    short: "Deployment",
    title: "Deployment & DevOps Plan",
    purpose: "Tells the AI how the app is hosted, built, and shipped",
    icon: "🚀",
    goldenRule: "Apps built without a deployment plan fail at ship time",
    sections: [
      { id: "hosting",      title: "Hosting Platform",       hint: "Where will the app run? e.g. Vercel, Netlify, AWS, Railway, Fly.io, GitHub Pages, self-hosted VPS.", kind: "line" },
      { id: "environments", title: "Environments",           hint: "List your environments and their purpose.\ne.g.\n- development: localhost\n- staging: preview.myapp.com\n- production: myapp.com", kind: "list" },
      { id: "cicd",         title: "CI/CD Pipeline",         hint: "How is code tested and deployed automatically? e.g. GitHub Actions: run tests on PR, deploy to Vercel on merge to main.", kind: "block", rows: 3 },
      { id: "envVars",      title: "Environment Variables",  hint: "List the env vars the app needs (not their values!). e.g.\nDATABASE_URL, STRIPE_SECRET_KEY, NEXT_PUBLIC_API_URL, SENTRY_DSN", kind: "list" },
      { id: "monitoring",   title: "Monitoring & Alerting",  hint: "How will errors and downtime be detected? e.g. Sentry for error tracking, UptimeRobot for availability, Datadog for logs.", kind: "line" },
    ],
  },
  {
    id: "agents",
    n: "10",
    short: "AGENTS.md",
    title: "AGENTS.md — AI Rules File",
    purpose: "Gives AI coding tools persistent rules for your project",
    icon: "🤖",
    goldenRule: "Without this, every AI session starts from scratch",
    sections: [
      { id: "projectSummary", title: "Project Summary",      hint: "1–2 paragraphs describing what the project does, who it's for, and the core tech stack. This is the first thing an AI agent reads.", kind: "block", rows: 4 },
      { id: "structure",    title: "Directory Structure",    hint: "Key folders and what they contain. e.g.\nsrc/components/ — UI components\nsrc/utils/ — helper functions\napi/ — backend routes", kind: "block", rows: 5 },
      { id: "conventions",  title: "Coding Conventions",     hint: "Rules the AI must follow every time. e.g.\n- Use functional React components only\n- No TypeScript — plain JS\n- All colours via CSS variables, never hardcoded", kind: "list" },
      { id: "commands",     title: "Key Commands",           hint: "Commands the agent needs to know. e.g.\nnpm run dev — start local server\nnpm test — run unit tests\nnpm run build — production build", kind: "list" },
      { id: "donts",        title: "Do Not",                 hint: "Explicit forbidden actions. e.g.\n- Do not add external packages without approval\n- Do not modify the database schema directly\n- Do not use inline styles", kind: "list" },
    ],
  },
];
